# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(485, 362)
        MainWindow.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.inputIdade = QtWidgets.QLineEdit(self.centralwidget)
        self.inputIdade.setObjectName("inputIdade")
        self.gridLayout.addWidget(self.inputIdade, 0, 3, 1, 1)
        self.inputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.inputNome.setObjectName("inputNome")
        self.gridLayout.addWidget(self.inputNome, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.inputTelefone = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTelefone.setObjectName("inputTelefone")
        self.gridLayout.addWidget(self.inputTelefone, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setRowCount(0)
        self.table.setColumnCount(3)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.table)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 4)
        self.btnRegistra = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegistra.setObjectName("btnRegistra")
        self.gridLayout.addWidget(self.btnRegistra, 1, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputNome, self.inputTelefone)
        MainWindow.setTabOrder(self.inputTelefone, self.inputIdade)
        MainWindow.setTabOrder(self.inputIdade, self.table)
        MainWindow.setTabOrder(self.table, self.btnRegistra)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agenda-qt"))
        self.label_2.setText(_translate("MainWindow", "Telefone"))
        self.label.setText(_translate("MainWindow", "Nome"))
        self.label_3.setText(_translate("MainWindow", "Idade"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Idade"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Telefone"))
        self.btnRegistra.setText(_translate("MainWindow", "Registrar contato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
